In [1]:
import pandas as pd
import datetime

In [2]:
# flights = pd.read_excel("../sound_proj/data/Raw-data/VTBS-SuvarnphumiAirport/2016/Leq0.5sec-VTBS-Date2MARto6MAR2016 ...xlsx", sheet_name='Billing')
flights = pd.read_excel("../sound_proj/data/Raw-data/MahPahLuangAirport/Billing-ท่าอากาศยานแม่ฟ้าหลวง เชียงราย.xlsx")
peaks = pd.read_csv("../sound_proj/data/Processed-data/output.csv")

In [3]:
flights

,ID,TYPE,A/D,RUNWAY,DATE,TIME,TIME1,FROM,TO,LOCAL DATE,LOCAL DATE.1
0,TLM547,B739,DEP,3,18,24,00:24:00,VTCT,VTBD,2562-03-18 00:00:00,7:24
1,TVJ130,A320,ARR,3,18,45,00:45:00,VTBS,VTCT,2562-03-18 00:00:00,7:45
2,TVJ131,A320,DEP,21,18,126,01:26:00,VTCT,VTBS,2562-03-18 00:00:00,8:26
3,NOK8714,B738,ARR,3,18,143,01:43:00,VTBD,VTCT,2562-03-18 00:00:00,8:43
4,BKP231,A320,ARR,3,18,153,01:53:00,VTBS,VTCT,2562-03-18 00:00:00,8:53
...,...,...,...,...,...,...,...,...,...,...,...
694,AIQ3205,A320,ARR,3,28,1455,14:55:00,VTBD,VTCT,2562-03-28 00:00:00,21:55
695,NOK8727,B738,DEP,3,28,1500,15:00:00,VTCT,VTBD,2562-03-28 00:00:00,22:00
696,TLM917,B739,ARR,3,28,1533,15:33:00,ZGHA,VTCT,2562-03-28 00:00:00,22:33
697,AIQ3206,A320,DEP,3,28,1538,15:38:00,VTCT,VTBD,2562-03-28 00:00:00,22:38
698,TLM549,B738,DEP,21,28,2302,23:02:00,VTCT,VTBD,2562-03-29 00:00:00,6:02

In [4]:
flights.rename(columns = {"LOCAL DATE.1":"LOCAL TIME"}, inplace = True)

In [5]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          699 non-null    object
 1   TYPE        699 non-null    object
 2   A/D         699 non-null    object
 3   RUNWAY      699 non-null    int64
 4   DATE        699 non-null    int64
 5   TIME        699 non-null    int64
 6   TIME1       699 non-null    object
 7   FROM        699 non-null    object
 8   TO          699 non-null    object
 9   LOCAL DATE  699 non-null    object
 10  LOCAL TIME  699 non-null    object
dtypes: int64(3), object(8)
memory usage: 60.2+ KB

In [6]:
def parse_date(dt):
	date_format = ['%m/%d/%Y %I:%M:%S %p:%f', '%Y/%m/%d %H:%M:%S', '%m/%d/%Y %H:%M:%S', '%Y/%m/%d %H:%M:%S',
	        	   '%Y-%m-%d', '%m-%d-%Y', '%d-%m-%Y', '%Y/%m/%d', '%m/%d/%Y', '%d/%m/%Y',
				   '%Y-%m-%d %H:%M:%S', '%m-%d-%Y %H:%M:%S', '%d-%m-%Y %H:%M:%S',
				   '%Y/%m/%d %H:%M:%S', '%m/%d/%Y %H:%M:%S', '%d/%m/%Y %H:%M:%S']

	for date_f in date_format:
		try:
			dateObject = datetime.datetime.strptime(dt, date_f)
			break
		except:
			dateObject = None
	
	return dateObject

In [16]:
def to_date(dt):
    try:
        dt = pd.to_datetime(dt)
        return dt
    except:
        dateObject = datetime.datetime.strptime(dt, '%Y-%m-%d %H:%M:%S')
        dt_str = dateObject.date()

        return datetime.date(dt_str.year-543, dt_str.month, dt_str.day)

In [7]:
def to_time(t):
    t_dt = pd.to_datetime(t)
    return t_dt.time()

In [12]:
flights['LOCAL DATE'] = flights['LOCAL DATE'].astype('str')
flights['LOCAL TIME'] = flights['LOCAL TIME'].astype('str')

In [17]:
flights["LOCAL DATE"].apply(lambda a: to_date(a))

0      2019-03-18
1      2019-03-18
2      2019-03-18
3      2019-03-18
4      2019-03-18
          ...
694    2019-03-28
695    2019-03-28
696    2019-03-28
697    2019-03-28
698    2019-03-29
Name: LOCAL DATE, Length: 699, dtype: object

In [10]:
flights["LOCAL DATE"] = flights["LOCAL DATE"].apply(lambda a: to_date(a))
flights["LOCAL TIME"] = flights["LOCAL TIME"].apply(lambda a: to_time(a))

flights["Datetime"] = pd.to_datetime(flights["LOCAL DATE"].astype('str') + " " + flights["LOCAL TIME"].astype('str'))

In [9]:
peaks["start_time"], peaks["end_time"] = pd.to_datetime(peaks["start_time"]), pd.to_datetime(peaks["end_time"])

In [10]:
flights.head()

  AIRCRAFT TYPE A/D RUNWAY  LOCAL DATE LOCAL TIME            Datetime
0          B738   D    01R  2016-03-02   00:02:00 2016-03-02 00:02:00
1          A333   D    01R  2016-03-02   00:13:00 2016-03-02 00:13:00
2          B744   D    01R  2016-03-02   00:16:00 2016-03-02 00:16:00
3          A388   D    01R  2016-03-02   00:18:00 2016-03-02 00:18:00
4          B772   D    01R  2016-03-02   00:20:00 2016-03-02 00:20:00

In [11]:
peaks.head()

   hours              start_time                end_time  peak_time  interval
0      0 2016-03-02 00:00:15.000 2016-03-02 00:00:44.500         59      29.5
1      0 2016-03-02 00:02:57.500 2016-03-02 00:03:34.500        392      37.0
2      0 2016-03-02 00:14:19.500 2016-03-02 00:14:56.500       1756      37.0
3      0 2016-03-02 00:17:19.500 2016-03-02 00:17:59.500       2119      40.0
4      0 2016-03-02 00:19:30.000 2016-03-02 00:20:03.500       2373      33.5

In [12]:
def phasedecide(date):
    dt = date.time()
    if (dt.hour >= 7) & (dt.hour < 19):
        return 1
    elif (dt.hour >= 19) & (dt.hour < 22):
        return 2
    else:
        return 3

In [13]:
min_peak, max_peak = min(peaks["start_time"]), max(peaks["end_time"])
flights = flights[(flights['Datetime'] > min_peak) & (flights['Datetime'] < max_peak)]
flights.head()

  AIRCRAFT TYPE A/D RUNWAY  LOCAL DATE LOCAL TIME            Datetime
0          B738   D    01R  2016-03-02   00:02:00 2016-03-02 00:02:00
1          A333   D    01R  2016-03-02   00:13:00 2016-03-02 00:13:00
2          B744   D    01R  2016-03-02   00:16:00 2016-03-02 00:16:00
3          A388   D    01R  2016-03-02   00:18:00 2016-03-02 00:18:00
4          B772   D    01R  2016-03-02   00:20:00 2016-03-02 00:20:00

In [14]:
flights['phase'] = flights['Datetime'].apply(lambda a: phasedecide(a))

C:\Users\User\AppData\Local\Temp\ipykernel_33864\3709348272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  flights['phase'] = flights['Datetime'].apply(lambda a: phasedecide(a))

In [15]:
lag_width = 30 # seconds

In [16]:
def match_cond(start,stop,date_time):
    return (date_time >= start-datetime.timedelta(milliseconds=lag_width*1000)) & (date_time <= stop+datetime.timedelta(milliseconds=lag_width*1000))

In [18]:
# test = []
# for start, stop, leq in zip(peaks['start_time'], peaks['end_time'], peaks['Leq']):
#     df = flights[match_cond(start,stop,flights['Datetime'])]
#     if len(df) > 0:
#         df = df.assign(Leq=leq)
#         test.append(df)

In [ ]:
pd.concat(test).reset_index(drop=True)

,ID,TYPE,A/D,RUNWAY,DATE,TIME,TIME1,FROM,TO,LOCAL DATE,LOCAL TIME,Datetime,phase,Leq
0,TVJ130,A320,ARR,3,20,43,00:43:00,VTBS,VTCT,2019-03-20,7:43:00,2019-03-20 07:43:00,1,75.863386
1,AIQ290,A320,DEP,21,20,107,01:07:00,VTCT,VMMC,2019-03-20,8:07:00,2019-03-20 08:07:00,1,71.913753
2,NOK8714,B738,ARR,3,20,149,01:49:00,VTBD,VTCT,2019-03-20,8:49:00,2019-03-20 08:49:00,1,74.193078
3,BKP231,A319,ARR,3,20,157,01:57:00,VTBS,VTCT,2019-03-20,8:57:00,2019-03-20 08:57:00,1,74.722909
4,TLM532,B39M,ARR,3,20,319,03:19:00,VTBD,VTCT,2019-03-20,10:19:00,2019-03-20 10:19:00,1,75.397119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128,THD136,A320,ARR,3,25,1305,13:05:00,VTBS,VTCT,2019-03-25,20:05:00,2019-03-25 20:05:00,2,73.800111
129,NOK8726,B738,ARR,3,25,1407,14:07:00,VTBD,VTCT,2019-03-25,21:07:00,2019-03-25 21:07:00,2,76.398686
130,AIQ831,A320,ARR,3,25,1440,14:40:00,WMKK,VTCT,2019-03-25,21:40:00,2019-03-25 21:40:00,2,74.954199
131,AIQ3205,A320,ARR,3,25,1447,14:47:00,VTBD,VTCT,2019-03-25,21:47:00,2019-03-25 21:47:00,2,74.270783
132,TLM546,B739,ARR,3,25,1546,15:46:00,VTBD,VTCT,2019-03-25,22:46:00,2019-03-25 22:46:00,3,76.053368

In [ ]:
matched = [flights[match_cond(start,stop,flights['Datetime'])] for start, stop in zip(peaks['start_time'], peaks['end_time']) if len(flights[match_cond(start,stop,flights['Datetime'])]) > 0]

In [ ]:
len(matched) / len(peaks)

0.4169278996865204

In [ ]:
df_matched = pd.concat(matched).reset_index(drop=True)
df_matched.head()

,ID,TYPE,A/D,RUNWAY,DATE,TIME,TIME1,FROM,TO,LOCAL DATE,LOCAL TIME,Datetime,phase
0,TVJ130,A320,ARR,3,20,43,00:43:00,VTBS,VTCT,2019-03-20,7:43:00,2019-03-20 07:43:00,1
1,AIQ290,A320,DEP,21,20,107,01:07:00,VTCT,VMMC,2019-03-20,8:07:00,2019-03-20 08:07:00,1
2,NOK8714,B738,ARR,3,20,149,01:49:00,VTBD,VTCT,2019-03-20,8:49:00,2019-03-20 08:49:00,1
3,BKP231,A319,ARR,3,20,157,01:57:00,VTBS,VTCT,2019-03-20,8:57:00,2019-03-20 08:57:00,1
4,TLM532,B39M,ARR,3,20,319,03:19:00,VTBD,VTCT,2019-03-20,10:19:00,2019-03-20 10:19:00,1

In [ ]:
df_matched = df_matched.drop(['DATE', 'TIME', 'TIME1'],axis=1)

In [ ]:
html = pd.read_html('https://en.wikipedia.org/wiki/List_of_airline_codes')
df_CALLSIGN_NAME = html[0]
df_CALLSIGN_NAME = df_CALLSIGN_NAME.dropna(subset=['ICAO'])
df_CALLSIGN_NAME.head()

,IATA,ICAO,Airline,Call sign,Country/Region,Comments
0,PR,BOI,2GO,ABAIR,Philippines,NaN
1,NaN,EVY,"34 Squadron, Royal Australian Air Force",Multiple,NaN,NaN
2,NaN,GNL,135 Airways,GENERAL,United States,NaN
16,2T,TBS,Timbis Air,TIMBIS,Kenya,NaN
17,3F,FIE,FlyOne Armenia,ARMRIDER,Armenia,NaN

In [ ]:
airline_names = dict(zip(df_CALLSIGN_NAME['ICAO'], df_CALLSIGN_NAME['Airline']))

In [ ]:
def callsign_name(call):
    c_name = ''.join(i for i in call if not i.isdigit())
    if c_name in list(df_CALLSIGN_NAME['ICAO']):
        return airline_names[c_name]
    else:
        return c_name

In [ ]:
df_airport_names = pd.read_csv('../sound_proj/data/aircraft-data/iata-icao.csv')
df_airport_names = df_airport_names.dropna(subset=['icao'])
df_airport_names.head()

,country_code,region_name,iata,icao,airport,latitude,longitude
0,AE,Ash Shariqah,SHJ,OMSJ,Sharjah International Airport,25.3286,55.5172
1,AE,Abu Zaby,AZI,OMAD,Al Bateen Executive Airport,24.4283,54.4581
2,AE,Al Fujayrah,FJR,OMFJ,Fujairah International Airport,25.1122,56.3240
3,AE,Abu Zaby,XSB,OMBY,Sir Bani Yas Airport,24.2836,52.5803
4,AE,Ra's al Khaymah,RKT,OMRK,Ras Al Khaimah International Airport,25.6135,55.9388

In [ ]:
airport_names = dict(zip(df_airport_names['icao'], df_airport_names['airport']))

In [ ]:
def call_airport_name(name):
    if name in list(df_airport_names['icao']):
        return airport_names[name]
    else:
        return name

In [ ]:
flights["airline_name"] = flights['ID'].apply(lambda a: callsign_name(a))

flights['POD_NAME'] = flights['FROM'].apply(lambda a: call_airport_name(a))
flights['DEST_NAME'] = flights['TO'].apply(lambda a: call_airport_name(a))

flights['POD_to_DEST'] = flights['POD_NAME'] + "➔" + flights['DEST_NAME']

In [ ]:
flights.to_csv("../sound_proj/matching_result.csv",index=False)

In [ ]:
# df_flight = pd.read_csv('../sound_proj/data/Processed-data/number_aircrafts.csv')
# df_flight.head()

In [ ]:
# df_flight['start_time'], df_flight['end_time'] = pd.to_datetime(df_flight['start_time']), pd.to_datetime(df_flight['end_time'])

In [ ]:
# n_aircraft_pred = [len(df_matched[(df_matched['Datetime'] >= start) & (df_matched['Datetime'] <= stop)]) for start, stop in zip(df_flight['start_time'], df_flight['end_time'])]

In [ ]:
# df_flight['aircrafts_pred'] = n_aircraft_pred

In [ ]:
# df_flight.head()

In [ ]:
# from sklearn.metrics import mean_squared_error
# mse = mean_squared_error(df_flight['aircrafts'], df_flight['aircrafts_pred'])
# print(mse)

235.2202380952381